apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: nitish
  name: test
  labels:
    app: hello-world
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/nitishnigam1989/deploy-python-openshift-tutorial.git"
      ref: master
    contextDir: /
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: nitish:1.0